# Generated by Django 3.0.7 on 2021-03-25 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Binance', 'Binance')], default='Binance', max_length=100)),
                ('api_key', encrypted_fields.fields.EncryptedCharField(default='', max_length=64)),
                ('api_secret', encrypted_fields.fields.EncryptedCharField(default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_btc', models.DecimalField(decimal_places=17, max_digits=30)),
                ('balance_usdt', models.DecimalField(decimal_places=2, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traderboard.TradingAccount')),
            ],
        ),
    ]
