# Generated by Django 3.0.7 on 2021-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0006_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='api_key',
            field=models.CharField(default='', max_length=64),
        ),
    ]
