# Generated by Django 3.0.7 on 2021-04-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0007_auto_20210330_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SnapshotProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_btc', models.DecimalField(decimal_places=8, max_digits=30)),
                ('balance_usdt', models.DecimalField(decimal_places=2, max_digits=30)),
                ('pnl_btc', models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True)),
                ('pnl_usdt', models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traderboard.Profile')),
            ],
        ),
    ]
