# Generated by Django 3.0.7 on 2021-04-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0008_auto_20210403_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshotprofile',
            name='pnl_btc',
        ),
        migrations.CreateModel(
            name='SnapshotProfileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traderboard.SnapshotProfile')),
            ],
        ),
    ]
