# Generated by Django 3.0.7 on 2021-05-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0011_auto_20210426_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_btc', models.DecimalField(decimal_places=8, max_digits=30)),
                ('balance_usdt', models.DecimalField(decimal_places=2, max_digits=30)),
                ('pnl_btc', models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True)),
                ('pnl_usdt', models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traderboard.TradingAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traderboard.SnapshotAccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='snapshotprofiledetails',
            name='snapshot',
        ),
        migrations.DeleteModel(
            name='SnapshotProfile',
        ),
        migrations.DeleteModel(
            name='SnapshotProfileDetails',
        ),
    ]
