# Generated by Django 3.0.7 on 2021-05-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0013_auto_20210510_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotaccount',
            name='balance_btc',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=30, null=True),
        ),
    ]
