# Generated by Django 3.2.3 on 2021-05-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0014_auto_20210520_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('asset', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('side', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traderboard.tradingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('asset', models.CharField(max_length=10)),
                ('base', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('side', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traderboard.tradingaccount')),
            ],
        ),
    ]
