# Generated by Django 3.2.3 on 2021-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0015_accounttrades_accounttransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotaccount',
            name='pnl_rel_btc',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='snapshotaccount',
            name='pnl_rel_usdt',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='snapshotaccount',
            name='pnl_btc',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='snapshotaccount',
            name='pnl_usdt',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=30, null=True),
        ),
    ]
