# Generated by Django 3.2.3 on 2021-06-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0016_auto_20210605_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshotaccount',
            name='pnl_rel_btc',
        ),
        migrations.RemoveField(
            model_name='snapshotaccount',
            name='pnl_rel_usdt',
        ),
    ]
