# Generated by Django 3.2.1 on 2021-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0017_auto_20210605_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nacc',
            field=models.IntegerField(default=0),
        ),
    ]
