# Generated by Django 3.2.1 on 2021-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0018_auto_20210818_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nacc',
            field=models.IntegerField(default=0),
        ),
    ]
