# Generated by Django 3.2.1 on 2021-09-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0018_profile_nacc'),
        ('traderboard', '0019_profile_nacc'),
    ]

    operations = [
    ]
