# Generated by Django 3.2.1 on 2021-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0020_merge_0018_profile_nacc_0019_profile_nacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttrades',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='accounttrades',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='accounttransactions',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='snapshotaccount',
            name='balance_btc',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='snapshotaccount',
            name='pnl_btc',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='snapshotaccountdetails',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
