# Generated by Django 3.2.1 on 2021-09-05 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0021_auto_20210904_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
