# Generated by Django 3.2.1 on 2021-09-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0022_tradingaccount_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nacc',
        ),
    ]
