# Generated by Django 3.2.1 on 2021-09-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0023_remove_profile_nacc'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='snapshotaccount',
            constraint=models.UniqueConstraint(fields=('account', 'created_at'), name='No snapshot duplicate'),
        ),
        migrations.AddConstraint(
            model_name='snapshotaccountdetails',
            constraint=models.UniqueConstraint(fields=('snapshot', 'asset'), name='No detail duplicate'),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(fields=('api_key', 'platform'), name='No api_key duplicate'),
        ),
    ]
