# Generated by Django 3.2.1 on 2021-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0025_accounttransactions_no transaction duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotaccount',
            name='balance_usdt',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
