# Generated by Django 3.2.1 on 2021-09-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0027_alter_snapshotaccount_pnl_usdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('platform', models.CharField(choices=[('Binance', 'Binance')], default='Binance', max_length=100)),
                ('symbol', models.CharField(default='Unknown', max_length=20)),
                ('asset', models.CharField(default='Unknown', max_length=20)),
                ('base', models.CharField(default='Unknown', max_length=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
            ],
        ),
        migrations.AddField(
            model_name='snapshotaccountdetails',
            name='price_btc',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='snapshotaccountdetails',
            name='price_usdt',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, null=True),
        ),
    ]
