# Generated by Django 3.0.7 on 2021-03-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0003_auto_20210327_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshotaccount',
            old_name='balance_usd',
            new_name='balance_usdt',
        ),
    ]
