# Generated by Django 3.0.7 on 2021-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0004_auto_20210327_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daily_pnl',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_pnl',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weekly_pnl',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True),
        ),
    ]
