# Generated by Django 3.0.7 on 2021-04-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderboard', '0010_snapshotprofile_pnl_btc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshotaccountdetails',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
        migrations.DeleteModel(
            name='SnapshotAccount',
        ),
        migrations.DeleteModel(
            name='SnapshotAccountDetails',
        ),
    ]
